### ISSUE TITLE
message called with incorrect number of arguments

### ISSUE THREAD

**Issue by yonelay11** [xiaohulugo/3DLineDetection#1]
Hello, Is it need to install openCV libraries? Beacuse they show me this message when I build with CMake.
CMake Error at CMakeLists.txt:11 (message):
  message called with incorrect number of arguments

**Comment by Baoook** [comment]
hi？Could u tell me how can I solve this problem？I come across the same problem。

**Comment by LetianLyndonRakutenLi** [comment]
Just comment the message line out LOL
